name: Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build API server
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build -o api-server ./cmd/api-server

    - name: Build worker
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build -o worker ./cmd/worker

    - name: Check
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u honnef.co/go/tools/cmd/staticcheck
        ./check.bash
